//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOEEntities : DbContext
    {
        public BOEEntities()
            : base("name=BOEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLA_APPLICATION_MODULE> TBLA_APPLICATION_MODULE { get; set; }
        public virtual DbSet<TBLA_CRUDLOG> TBLA_CRUDLOG { get; set; }
        public virtual DbSet<TBLA_LOGIN_STATUS> TBLA_LOGIN_STATUS { get; set; }
        public virtual DbSet<TBLA_PASSWORD> TBLA_PASSWORD { get; set; }
        public virtual DbSet<TBLA_SECURITY_QUESTION> TBLA_SECURITY_QUESTION { get; set; }
        public virtual DbSet<TBLA_UI_MODULE> TBLA_UI_MODULE { get; set; }
        public virtual DbSet<TBLA_UI_PAGE> TBLA_UI_PAGE { get; set; }
        public virtual DbSet<TBLA_URL> TBLA_URL { get; set; }
        public virtual DbSet<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING { get; set; }
        public virtual DbSet<TBLA_USER_GROUP> TBLA_USER_GROUP { get; set; }
        public virtual DbSet<TBLA_USER_INFORMATION> TBLA_USER_INFORMATION { get; set; }
        public virtual DbSet<TBLB_COA> TBLB_COA { get; set; }
        public virtual DbSet<TBLB_COMPANY> TBLB_COMPANY { get; set; }
        public virtual DbSet<TBLB_LOCATION> TBLB_LOCATION { get; set; }
        public virtual DbSet<TBLT_COA_TRANSACTION_DETAIL> TBLT_COA_TRANSACTION_DETAIL { get; set; }
        public virtual DbSet<TBLT_COA_TRANSACTION_MASTER> TBLT_COA_TRANSACTION_MASTER { get; set; }
        public virtual DbSet<TBLT_SURVEY_COMMUNICATION> TBLT_SURVEY_COMMUNICATION { get; set; }
        public virtual DbSet<TBLT_SURVEY_DEPOSIT> TBLT_SURVEY_DEPOSIT { get; set; }
    }
}
