//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLA_LOGIN_STATUS
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public bool PresentLogInStatus { get; set; }
        public System.DateTime LogInTime { get; set; }
        public System.DateTime LogOutTime { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public bool ForcedLogOutStatus { get; set; }
    
        public virtual TBLB_COMPANY TBLB_COMPANY { get; set; }
        public virtual TBLB_LOCATION TBLB_LOCATION { get; set; }
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION { get; set; }
    }
}
