//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLA_SECURITY_QUESTION
    {
        public System.Guid ID { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecutiryAnswer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual TBLB_COMPANY TBLB_COMPANY { get; set; }
        public virtual TBLB_LOCATION TBLB_LOCATION { get; set; }
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION { get; set; }
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION1 { get; set; }
    }
}
