//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLA_UI_MODULE
    {
        public TBLA_UI_MODULE()
        {
            this.TBLA_UI_PAGE = new HashSet<TBLA_UI_PAGE>();
            this.TBLA_URL = new HashSet<TBLA_URL>();
            this.TBLA_USER_ACTION_MAPPING = new HashSet<TBLA_USER_ACTION_MAPPING>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string UIName { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
    
        public virtual TBLB_COMPANY TBLB_COMPANY { get; set; }
        public virtual TBLB_LOCATION TBLB_LOCATION { get; set; }
        public virtual ICollection<TBLA_UI_PAGE> TBLA_UI_PAGE { get; set; }
        public virtual ICollection<TBLA_URL> TBLA_URL { get; set; }
        public virtual ICollection<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING { get; set; }
    }
}
