//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLA_USER_INFORMATION
    {
        public TBLA_USER_INFORMATION()
        {
            this.TBLA_CRUDLOG = new HashSet<TBLA_CRUDLOG>();
            this.TBLA_LOGIN_STATUS = new HashSet<TBLA_LOGIN_STATUS>();
            this.TBLA_PASSWORD = new HashSet<TBLA_PASSWORD>();
            this.TBLA_PASSWORD1 = new HashSet<TBLA_PASSWORD>();
            this.TBLA_SECURITY_QUESTION = new HashSet<TBLA_SECURITY_QUESTION>();
            this.TBLA_SECURITY_QUESTION1 = new HashSet<TBLA_SECURITY_QUESTION>();
            this.TBLA_USER_ACTION_MAPPING = new HashSet<TBLA_USER_ACTION_MAPPING>();
            this.TBLA_USER_ACTION_MAPPING1 = new HashSet<TBLA_USER_ACTION_MAPPING>();
            this.TBLA_USER_GROUP = new HashSet<TBLA_USER_GROUP>();
            this.TBLA_USER_GROUP1 = new HashSet<TBLA_USER_GROUP>();
            this.TBLB_LOCATION = new HashSet<TBLB_LOCATION>();
            this.TBLT_SURVEY_COMMUNICATION = new HashSet<TBLT_SURVEY_COMMUNICATION>();
            this.TBLT_SURVEY_COMMUNICATION1 = new HashSet<TBLT_SURVEY_COMMUNICATION>();
            this.TBLT_SURVEY_DEPOSIT = new HashSet<TBLT_SURVEY_DEPOSIT>();
            this.TBLT_SURVEY_DEPOSIT1 = new HashSet<TBLT_SURVEY_DEPOSIT>();
            this.TBLA_USER_INFORMATION1 = new HashSet<TBLA_USER_INFORMATION>();
            this.TBLA_USER_INFORMATION11 = new HashSet<TBLA_USER_INFORMATION>();
        }
    
        public System.Guid ID { get; set; }
        public string UserFullName { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public System.Guid PasswordID { get; set; }
        public System.Guid SecurityQuestionID { get; set; }
        public bool IsEMailVerified { get; set; }
        public bool IsPhoneNoVerified { get; set; }
        public bool IsActive { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public int UserGroupID { get; set; }
        public string EmployeeCode { get; set; }
        public string TradingCode { get; set; }
        public string BOCode { get; set; }
        public Nullable<bool> IsClient { get; set; }
    
        public virtual ICollection<TBLA_CRUDLOG> TBLA_CRUDLOG { get; set; }
        public virtual ICollection<TBLA_LOGIN_STATUS> TBLA_LOGIN_STATUS { get; set; }
        public virtual ICollection<TBLA_PASSWORD> TBLA_PASSWORD { get; set; }
        public virtual ICollection<TBLA_PASSWORD> TBLA_PASSWORD1 { get; set; }
        public virtual ICollection<TBLA_SECURITY_QUESTION> TBLA_SECURITY_QUESTION { get; set; }
        public virtual ICollection<TBLA_SECURITY_QUESTION> TBLA_SECURITY_QUESTION1 { get; set; }
        public virtual ICollection<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING { get; set; }
        public virtual ICollection<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING1 { get; set; }
        public virtual ICollection<TBLA_USER_GROUP> TBLA_USER_GROUP { get; set; }
        public virtual ICollection<TBLA_USER_GROUP> TBLA_USER_GROUP1 { get; set; }
        public virtual TBLA_USER_GROUP TBLA_USER_GROUP2 { get; set; }
        public virtual ICollection<TBLB_LOCATION> TBLB_LOCATION { get; set; }
        public virtual ICollection<TBLT_SURVEY_COMMUNICATION> TBLT_SURVEY_COMMUNICATION { get; set; }
        public virtual ICollection<TBLT_SURVEY_COMMUNICATION> TBLT_SURVEY_COMMUNICATION1 { get; set; }
        public virtual ICollection<TBLT_SURVEY_DEPOSIT> TBLT_SURVEY_DEPOSIT { get; set; }
        public virtual ICollection<TBLT_SURVEY_DEPOSIT> TBLT_SURVEY_DEPOSIT1 { get; set; }
        public virtual TBLB_COMPANY TBLB_COMPANY { get; set; }
        public virtual TBLB_LOCATION TBLB_LOCATION1 { get; set; }
        public virtual ICollection<TBLA_USER_INFORMATION> TBLA_USER_INFORMATION1 { get; set; }
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION2 { get; set; }
        public virtual ICollection<TBLA_USER_INFORMATION> TBLA_USER_INFORMATION11 { get; set; }
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION3 { get; set; }
    }
}
