//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLA_URL
    {
        public TBLA_URL()
        {
            this.TBLA_USER_ACTION_MAPPING = new HashSet<TBLA_USER_ACTION_MAPPING>();
        }
    
        public System.Guid ID { get; set; }
        public string ControllerName { get; set; }
        public string ClassName { get; set; }
        public string Url { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> UIApplicationID { get; set; }
        public Nullable<int> UIModulID { get; set; }
        public Nullable<int> UIPageID { get; set; }
    
        public virtual TBLA_APPLICATION_MODULE TBLA_APPLICATION_MODULE { get; set; }
        public virtual TBLA_UI_MODULE TBLA_UI_MODULE { get; set; }
        public virtual TBLA_UI_PAGE TBLA_UI_PAGE { get; set; }
        public virtual TBLB_COMPANY TBLB_COMPANY { get; set; }
        public virtual TBLB_LOCATION TBLB_LOCATION { get; set; }
        public virtual ICollection<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING { get; set; }
    }
}
