//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLA_UI_PAGE
    {
        public TBLA_UI_PAGE()
        {
            this.TBLA_CRUDLOG = new HashSet<TBLA_CRUDLOG>();
            this.TBLA_URL = new HashSet<TBLA_URL>();
            this.TBLA_USER_ACTION_MAPPING = new HashSet<TBLA_USER_ACTION_MAPPING>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string UIPageName { get; set; }
        public int ApplicationID { get; set; }
        public int ModuleID { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.Guid> UrlID { get; set; }
    
        public virtual TBLA_APPLICATION_MODULE TBLA_APPLICATION_MODULE { get; set; }
        public virtual ICollection<TBLA_CRUDLOG> TBLA_CRUDLOG { get; set; }
        public virtual TBLA_UI_MODULE TBLA_UI_MODULE { get; set; }
        public virtual TBLB_COMPANY TBLB_COMPANY { get; set; }
        public virtual TBLB_LOCATION TBLB_LOCATION { get; set; }
        public virtual ICollection<TBLA_URL> TBLA_URL { get; set; }
        public virtual ICollection<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING { get; set; }
    }
}
