//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLB_COA
    {
        public int COAID { get; set; }
        public int CostCenterID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int Level { get; set; }
        public string GLName { get; set; }
        public string GLACNO { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string POSTFLAG { get; set; }
        public string DRCR { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string AuthorizedStatus { get; set; }
        public string ActionStatus { get; set; }
    }
}
