//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLB_COMPANY
    {
        public TBLB_COMPANY()
        {
            this.TBLA_APPLICATION_MODULE = new HashSet<TBLA_APPLICATION_MODULE>();
            this.TBLA_CRUDLOG = new HashSet<TBLA_CRUDLOG>();
            this.TBLA_LOGIN_STATUS = new HashSet<TBLA_LOGIN_STATUS>();
            this.TBLA_PASSWORD = new HashSet<TBLA_PASSWORD>();
            this.TBLA_SECURITY_QUESTION = new HashSet<TBLA_SECURITY_QUESTION>();
            this.TBLA_UI_MODULE = new HashSet<TBLA_UI_MODULE>();
            this.TBLA_UI_PAGE = new HashSet<TBLA_UI_PAGE>();
            this.TBLA_URL = new HashSet<TBLA_URL>();
            this.TBLA_USER_ACTION_MAPPING = new HashSet<TBLA_USER_ACTION_MAPPING>();
            this.TBLA_USER_GROUP = new HashSet<TBLA_USER_GROUP>();
            this.TBLA_USER_INFORMATION = new HashSet<TBLA_USER_INFORMATION>();
            this.TBLB_LOCATION = new HashSet<TBLB_LOCATION>();
            this.TBLT_SURVEY_DEPOSIT = new HashSet<TBLT_SURVEY_DEPOSIT>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string EMail { get; set; }
        public string RegisterationNo { get; set; }
        public Nullable<System.DateTime> RegisterationDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public bool IsActive { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual ICollection<TBLA_APPLICATION_MODULE> TBLA_APPLICATION_MODULE { get; set; }
        public virtual ICollection<TBLA_CRUDLOG> TBLA_CRUDLOG { get; set; }
        public virtual ICollection<TBLA_LOGIN_STATUS> TBLA_LOGIN_STATUS { get; set; }
        public virtual ICollection<TBLA_PASSWORD> TBLA_PASSWORD { get; set; }
        public virtual ICollection<TBLA_SECURITY_QUESTION> TBLA_SECURITY_QUESTION { get; set; }
        public virtual ICollection<TBLA_UI_MODULE> TBLA_UI_MODULE { get; set; }
        public virtual ICollection<TBLA_UI_PAGE> TBLA_UI_PAGE { get; set; }
        public virtual ICollection<TBLA_URL> TBLA_URL { get; set; }
        public virtual ICollection<TBLA_USER_ACTION_MAPPING> TBLA_USER_ACTION_MAPPING { get; set; }
        public virtual ICollection<TBLA_USER_GROUP> TBLA_USER_GROUP { get; set; }
        public virtual ICollection<TBLA_USER_INFORMATION> TBLA_USER_INFORMATION { get; set; }
        public virtual ICollection<TBLB_LOCATION> TBLB_LOCATION { get; set; }
        public virtual ICollection<TBLT_SURVEY_DEPOSIT> TBLT_SURVEY_DEPOSIT { get; set; }
    }
}
