//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLT_COA_TRANSACTION_MASTER
    {
        public int COATRANSACTIONID { get; set; }
        public int VoucherTypeID { get; set; }
        public string VoucherNO { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public int CostCenterID { get; set; }
        public int BranchID { get; set; }
        public string DocRef { get; set; }
        public string Narration { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string AuthorizedStatus { get; set; }
        public string ActionStatus { get; set; }
    }
}
