//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOEService.Entites.BOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLT_SURVEY_COMMUNICATION
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string ComnucationType { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Reason { get; set; }
        public string FeedBack { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public System.DateTime CommunicationDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
    
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION { get; set; }
        public virtual TBLA_USER_INFORMATION TBLA_USER_INFORMATION1 { get; set; }
    }
}
